return  {
    { "catppuccin/nvim",          name = "catppuccin" },
    { "Everblush/everblush.nvim", name = "everblush" },
    { "jesseleite/nvim-noirbuddy", name = "noirbuddy", lazy = false, priority = 1000, dependencies = { "tjdevries/colorbuddy.nvim", branch = "dev" },
    },
    { "oxfist/night-owl.nvim",           lazy = false, priority = 1000, },
    { "folke/tokyonight.nvim",           lazy = false, priority = 1000, opts = {}, },
    { "navarasu/onedark.nvim" },
    { "sainnhe/gruvbox-material" },
    { "nyoom-engineering/oxocarbon.nvim" },
    { "rebelot/kanagawa.nvim" },
    { "Yazeed1s/oh-lucy.nvim" },
    { "kvrohit/mellow.nvim" },
    { "AlexvZyl/nordic.nvim",            lazy = false, priority = 1000, },
    { "marko-cerovac/material.nvim" },
    { "ribru17/bamboo.nvim",             lazy = false, priority = 1000, },
    { "daschw/leaf.nvim" },
    { "Verf/deepwhite.nvim",             lazy = false, priority = 1000 },
    { "daschw/leaf.nvim",                lazy = false, priority = 1000 },
}
